include/net: bond_alb: Fix conflicting function return types
bond_tlb_xmit() and bond_alb_xmit() is declared with netdev_tx_t return
type that is a typedef for an enum type. But bond_alb header got them
as int types. Fix the conflicts.

This fixes the following warnings by GCC:

../drivers/net/bonding/bond_alb.c:1353:13: warning: conflicting types for 'bond_tlb_xmit' due to enum/integer mismatch; have 'netdev_tx_t(struct sk_buff *, struct net_device *)' {aka 'enum netdev_tx(struct sk_buff *, struct net_device *)'} [-Wenum-int-mismatch]
 1353 | netdev_tx_t bond_tlb_xmit(struct sk_buff *skb, struct net_device *bond_dev)
      |             ^~~~~~~~~~~~~
In file included from ../include/net/bonding.h:30,
                 from ../drivers/net/bonding/bond_alb.c:40:
../include/net/bond_alb.h:176:5: note: previous declaration of 'bond_tlb_xmit' with type 'int(struct sk_buff *, struct net_device *)'
  176 | int bond_tlb_xmit(struct sk_buff *skb, struct net_device *bond_dev);
      |     ^~~~~~~~~~~~~
../drivers/net/bonding/bond_alb.c:1391:13: warning: conflicting types for 'bond_alb_xmit' due to enum/integer mismatch; have 'netdev_tx_t(struct sk_buff *, struct net_device *)' {aka 'enum netdev_tx(struct sk_buff *, struct net_device *)'} [-Wenum-int-mismatch]
 1391 | netdev_tx_t bond_alb_xmit(struct sk_buff *skb, struct net_device *bond_dev)
      |             ^~~~~~~~~~~~~
../include/net/bond_alb.h:175:5: note: previous declaration of 'bond_alb_xmit' with type 'int(struct sk_buff *, struct net_device *)'
  175 | int bond_alb_xmit(struct sk_buff *skb, struct net_device *bond_dev);
      |     ^~~~~~~~~~~~~

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>