{dm, device-mapper}: Fix conflicting function prototypes
Use the function prototypes of drivers/md/dm.h at include/linux/device-mapper.h
and remove the functions at drivers/md/dm.h since device-mapper.h is included
there.

This fixes the following warnings by GCC:

In file included from ../drivers/md/dm-uevent.c:27:
../drivers/md/dm.h:67:20: warning: conflicting types for 'dm_table_get_type' due to enum/integer mismatch; have 'enum dm_queue_mode(struct dm_table *)' [-Wenum-int-mismatch]
   67 | enum dm_queue_mode dm_table_get_type(struct dm_table *t);
      |                    ^~~~~~~~~~~~~~~~~
In file included from ../drivers/md/dm.h:14:
../include/linux/device-mapper.h:448:10: note: previous declaration of 'dm_table_get_type' with type 'unsigned int(struct dm_table *)'
  448 | unsigned dm_table_get_type(struct dm_table *t);
      |          ^~~~~~~~~~~~~~~~~
../drivers/md/dm.h:79:6: warning: conflicting types for 'dm_set_md_type' due to enum/integer mismatch; have 'void(struct mapped_device *, enum dm_queue_mode)' [-Wenum-int-mismatch]
   79 | void dm_set_md_type(struct mapped_device *md, enum dm_queue_mode type);
      |      ^~~~~~~~~~~~~~
../include/linux/device-mapper.h:445:6: note: previous declaration of 'dm_set_md_type' with type 'void(struct mapped_device *, unsigned int)'
  445 | void dm_set_md_type(struct mapped_device *md, unsigned type);
      |      ^~~~~~~~~~~~~~
../drivers/md/dm.h:80:20: warning: conflicting types for 'dm_get_md_type' due to enum/integer mismatch; have 'enum dm_queue_mode(struct mapped_device *)' [-Wenum-int-mismatch]
   80 | enum dm_queue_mode dm_get_md_type(struct mapped_device *md);
      |                    ^~~~~~~~~~~~~~
../include/linux/device-mapper.h:446:10: note: previous declaration of 'dm_get_md_type' with type 'unsigned int(struct mapped_device *)'
  446 | unsigned dm_get_md_type(struct mapped_device *md);
      |          ^~~~~~~~~~~~~~

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>